name: {{cookiecutter.project_slug}}

channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults

dependencies:
  # dependencies
  - python=3.10
  - numpy>=1.25.2
  # dev dependencies
  - ruff
  - pre-commit
  # build dependencies
  - pip
  - pip:
    # dependencies
    - mlflow>=2.6.0
    - typer[all]>=0.9.0
    # dev dependencies
    # ## ci
    - pdoc
    - nox
    # ## linting
    - black
    - mypy
    - isort
    # ## notebook
    - notebook>=7.0.3
    - voila>=0.5.1
    - ipywidgets>=8.1.0
    # ## pytest
    - pytest>=7.4.0
    - pytest-cov>=4.1.0
    - pytest-mock>=3.11.1
